# Generated by Django 4.2.13 on 2024-07-10 19:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carseries',
            options={'verbose_name': 'Car Series', 'verbose_name_plural': 'Car Series'},
        ),
        migrations.AddField(
            model_name='carmake',
            name='accident_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carmake',
            name='engine',
            field=models.CharField(choices=[('GAS', 'Gas'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybrid'), ('ELECTRIC', 'Electric'), ('Hydrogen', 'Hydrogen'), ('OTHER', 'Other')], default='Gas', max_length=1000),
        ),
        migrations.AddField(
            model_name='carmake',
            name='origin_country',
            field=models.CharField(default='USA', max_length=1000),
        ),
        migrations.AddField(
            model_name='carmake',
            name='other_data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='series',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='makes', to='app.carseries'),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='year_manufactured',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)], verbose_name='year_manufactued'),
        ),
    ]
