# Generated by Django 4.2.13 on 2024-07-11 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_carmake_other_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmake',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
