# Generated by Django 4.2.13 on 2024-07-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_carmake_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmake',
            name='engine',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric'), ('Hydrogen', 'Hydrogen'), ('Other', 'Other')], default='Gas', max_length=1000),
        ),
    ]
